---

# Instalando o Node.js

- name: "Instalando o Node.js versão {{ nodejs_suse_version }}"
  zypper:
    name: "{{ nodejs_suse_packages }}"
    state: present
    update_cache: yes
    disable_gpg_check: yes
  become: true
  tags:
    - nodejs